name: Build React
 
on:
  # Triggers the workflow on push/PR for main, staging & development branches
  push:
    branches: [ main, staging, development, workflow-test ]
  pull_request:
    branches: [ main, staging, development, workflow-test ]

  # Enable manual run from the actions tab
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.8]

    steps:
      # Get the repo to enable access by the job
      - uses: actions/checkout@v2

      # Install Node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # Build
      - name: Build PR_Visualizer
        run: |
          cd app/ 
          npm run build