name: Build React
 
on:
  # Triggers the workflow on push/PR for main, staging & development branches
  push:
    branches: [ main, staging, development ]
  pull_request:
    branches: [ main, staging, development  ]

  # Enable manual run from the actions tab
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      # Get the repo to enable access by the job
      - uses: actions/checkout@v2
      - name: Install node

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: checkout to the app directory
        run: cd app/

      - name: Build React-App
        run: npm run build